pipelines:
  ops-manual-test:
    group: Kafka-Manual-Producer
    label_template: "${COUNT}"
    locking: off
    environment_variables:
      MESSAGE: |
        echo "Hello"
    materials:
      git-repo:
        git: git@github.com:cassioliveiram/renataecassio.git
        branch: master
        auto_update: false
    stages:
    - create_message_file:
        fetch_materials: no
        approval:
          type: manual
        jobs:
          create_message:
            tasks:
              - script: |
                  set -e ## exit on first error
                  echo "$MESSAGE"