pipelines:
  terraformTag:
    group: DevOps
    label_template: ${COUNT}
    materials:
      git-repo:
        url: git@github.com:cassioliveiram/terraform-kind-module.git
        defaultBranch: master
        auto_update: false
    stages:
      - list-and-publish-tags:
          fetch_materials: no
          approval:
            type: manual
          jobs:
            list-and-publish-tags:
              environment_variables:
                VERSION_TYPE: "patch"
              tasks:
                - script: |
                    set -e ## exit on first error
                    cd pipeline
                    bash scripts/manage-repo-tags-sh "$VERSION_TYPE"
